// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyXNPgXFDPvjzbkQlNVlqfT7lDD2JULYM',
    appId: '1:24037222446:web:6af6333dd55a0607d7d7bf',
    messagingSenderId: '24037222446',
    projectId: 'playstatoinproject',
    authDomain: 'playstatoinproject.firebaseapp.com',
    storageBucket: 'playstatoinproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRuhb-f2_YgwqguzZ_IOhLMb7HPaQ1p_g',
    appId: '1:24037222446:android:abbb31682c8fd8bbd7d7bf',
    messagingSenderId: '24037222446',
    projectId: 'playstatoinproject',
    storageBucket: 'playstatoinproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxlOYfhZYBTMDiAOxRowteARNaBt7bbXQ',
    appId: '1:24037222446:ios:ff3d593bb352777cd7d7bf',
    messagingSenderId: '24037222446',
    projectId: 'playstatoinproject',
    storageBucket: 'playstatoinproject.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxlOYfhZYBTMDiAOxRowteARNaBt7bbXQ',
    appId: '1:24037222446:ios:ff3d593bb352777cd7d7bf',
    messagingSenderId: '24037222446',
    projectId: 'playstatoinproject',
    storageBucket: 'playstatoinproject.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyXNPgXFDPvjzbkQlNVlqfT7lDD2JULYM',
    appId: '1:24037222446:web:3f44852f82e2b9efd7d7bf',
    messagingSenderId: '24037222446',
    projectId: 'playstatoinproject',
    authDomain: 'playstatoinproject.firebaseapp.com',
    storageBucket: 'playstatoinproject.appspot.com',
  );
}
